version: '3'

services:
  training-api:
    container_name: sastraining-api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4001:4001
    depends_on:
      - postgres

  training-spa:
    container_name: sastraining-spa
    build:
      context: ../practice-spa
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=http://localhost:4001
      
  postgres:
    image: postgres
    container_name: postgrescp
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  pgdata:
